# Generated by Django 2.0.1 on 2018-01-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0002_auto_20180118_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='publickey',
            name='key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publickey',
            name='fingerprint',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
